### ISSUE TITLE
One hard-wired English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [drachels/moodle-mod_hotquestion#19]
Hi,
I was trying your Hot question plugin for Moodle and I noticed that it seems that you have one English language string variable (inputquestion | hotquestion) as 'Submit your question here: ', but the plugin uses both this string variable (green rectangle) for the option text and a string constant (orange rectangle) for the default value, as seen in the attached screen of my Spanish language local 3.2.1 server:
![hot question hardwired string](https://cloud.githubusercontent.com/assets/2671923/22841503/7d19a36a-ef97-11e6-8de4-7cd9c5c83424.png)

**Comment by drachels** [comment]
You can go to the Hot Questions settings page and change the text to whatever you want the default to be. The change was made to make the Hot Question plugin more general purpose by letting a teacher change the submission wording at the time they create a Hot Question activity. I also made it a setting so that you can change the default wording on the settings page, but the wording can still be changed at the time of creating the activity. For instance, if you are using Hot Question as a "Suggestion Box" you do not want the activity to be labeled, "Submit your question here:."
I just realized that I probably do need to make a Help entry to explain this.

**Comment by drachels** [comment]
Added help entry.
