### ISSUE TITLE
get_string('post') for the submit button does not work in each language

### ISSUE THREAD

**Issue by lucaboesch** [drachels/moodle-mod_hotquestion#27]
Thanks for your great Plugin!
I want to notice you that the core 'post' string does not fit in each language.
You see, 'post' can mean two things:
The 'post' as the noun. It's the post itself.
And then there's 'post' the verb. I'm about to post a question.
Core 'post' is the noun.
In some languages the verb and the noun differ.
I'd kindly advise you to take into consideration a propietary get_string('post', 'mod_hotquestion') string which would contain the verb. Even if in english, that is a homonym.

**Comment by lucaboesch** [comment]
Keep safe, Al!
I wish you all the best.
Luca

**Comment by drachels** [comment]
Got lucky with the storm. The eye of the hurricane passed about 50 miles to the southeast so we just had lots of wind and rain. Our only damage is a yard full of small twigs and lots of leaves.
Took me a while to find where the language string for the "Post" button is being applied as it is not in the logical place for it, and I have not taken the time to move it since I took over responsibility for the plug in. It can be changed and customized just like any other language string. It is "Post" in core moodle.php but I will see about adding a specific Hot Question language string in the next release.

**Comment by drachels** [comment]
Code changed in mod_form.php to use new language string.
