### ISSUE TITLE
Removing the last round does not remove the round itself, only the content

### ISSUE THREAD

**Issue by waelde** [drachels/moodle-mod_hotquestion#35]
I don't know if this is intentional, but if I start a new round (accidently) and then try to remove it, it does only remove the questions and not the new round. The problem here is that if I want the old questions on the current page, there is no way to do that yet (to reverse the process). If I delete a round in between the page does vanish, so I am wondering why it does not work with the last round.

**Comment by drachels** [comment]
What you describe, **is** the expected behavior. When you delete a round its contents are gone and cannot be recovered. You can't tell it with the "last round" but you are getting a new page, it is just empty of questions.
I think you might not be using the latest Hot Question 3.5.3+ because it has a pop-up that asks you, "Confirm you want to delete round" to help prevent "accidental" deletions. Please check your version and upgrade, if you are not using 3.5.3+.

**Comment by waelde** [comment]
Thank you for the quick answer!
we are indeed using 3.5.3+. The Problem is not the accidental deletion of rounds (the pop up works) but the accidential starting of rounds (where there is no po-up) that can be deleted but then I am stuck with a blank page and not the current round that i had before, because the process is not reversable. 
I wanted to report this behaviour because i was testing the plugins for our moodle and found it a bit odd but if it is indeed intentional we will adapt to it if there should ever be a problem with that behaviour in the future.
Thank you!

**Comment by drachels** [comment]
I am so sorry that I just now realized that you and I were concerned about two different situations. I thought you were talking about the, Delete round, tool button, when it appears you were concerned with the, Open a new round, tool button. I will investigate and see what I can do. Easiest thing would be to add a confirmation popup with a warning that opening a new round would lock the previous round.

In the past, on multiple occasions, I have wanted to add to a closed round, too. I will investigate the possibility of making an old round become the current round or, maybe making a previous round accept new entries.

Please be patient as right now my time for working on this is limited due to my wife is presently undergoing a post operative preventive round of chemo therapy for pancreatic cancer. She is one month into a scheduled three month process, but it is going to probably be extended to four months due to her poor tolerance to one of the drugs.

**Comment by drachels** [comment]
Created new version 3.6.0 branch with confirmation popup. Will probably be tomorrow before I put on moodle.org as I have only tested on Moodle 3.7 so far. Need to test down to Moodle 2.8.

**Comment by waelde** [comment]
It is not at all urgent, it was just something that we noticed and thought could be improved.
Please take your time. And I wish your wife a good recovery (according to the circumstances).
Thank you : )

**Comment by drachels** [comment]
Confirmation popup when opening a New round, is included in the new Hot Question 3.6.0 (Build 209062400) released today 20190625.
