### ISSUE TITLE
Anonymously posted suggestions are not displayed to author or group members

### ISSUE THREAD

**Issue by FloMiLe** [drachels/moodle-mod_hotquestion#44]
With group mode 'separate groups', anonymously posted suggestions are neither displayed to the author nor to other members of the group. Only the trainer can see them.

I guess this in not intentional since it does not allow voting for such suggestions.

**Comment by drachels** [comment]
Actually, I tend to lean toward it being intentional. Anonymous is NOT a member of any group. So, I would suggest using the new version 3.9.1, do NOT allow anonymous entries, and then use the new setting to hide author names. That way, all entries will be anonymous to the students, but not to the teacher. Essentially, it has always been that way as the info for anonymous entries is in the logs.

**Comment by FloMiLe** [comment]
I thing I would disagree on the generalization concerning anonymous entries. In the Feedback activity, for example, anonymous submissions are still attributed to a group and can be filtered by group.

But your new version does, of course, offer a solution to that issue. So maybe that has turned into a non-issue then.
