### ISSUE TITLE
Are Completion & grades considered of interest ?

### ISSUE THREAD

**Issue by moodleulpgc** [drachels/moodle-mod_hotquestion#53]
Hi, I've discovered this plugin recently. I've seen as a good tool to add in a flipped classroom environment, to let students asks questions about materials (readings, videos) **before** the actual class.    
To encourage participation I see as needed a way to rate the number or question asked by a student and/or participation through voting other student's questions. Maybe with a grading system. Because then the teacher can set finalization conditions like "asking N questions", but additionally, with grades, can say completed when grade > X and grades can be obtained but posting new questions and by voting, so encouraging voting. 

I have a version of the plugin with some additions to allow completion rules and rating (grades). I'm considering all questions posted by a student in an instance, and votes received. There is no provision for separate "rounds", or grading separately each round. 

Do you think that adding optional completion rules and ratings/grades are desirable improvements for this plugin? Or rather they will disturb the intended use?  Would you consider integrating that improvements in the regular plugin? I currently have customizations working on a 3.9 installation, but planning to add to 4.0.2 for moodle 4.

**Comment by drachels** [comment]
Hi Enrique,
Yes, rating student questions and completion rules are on my "possibilities" list but for me they have been a lower priority than other things simply because to me that was possible either by using a forum or database activity. If you can provide me with a copy of your code or a link to it, I will see what I can do about adding the new capabilities sooner, rater than later.

**Comment by moodleulpgc** [comment]
Hi, Al, please find enclosed a version for moodle 3.9 with completions and ratings/grades. 
We count ratings by questions asked and by votes emitted. A question counts more for the rating of the author if has more heat (votes by others) and if the questions has higher priority.  The weights are configurable per instance. 

All new lines are marqued with // ecastro ULPGC comments

[hotquestion_401_ecastro-ULPGC.zip](https://github.com/drachels/moodle-mod_hotquestion/files/8556937/hotquestion_401_ecastro-ULPGC.zip)

**Comment by drachels** [comment]
My first attempt to use your code was by replacing the code for a Hot Question 4.0.1 in a Moodle 3.3 site, which resulted in a fatal crash: Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/moodle33/mod/hotquestion/lib.php on line 671. I am pretty sure it is due to the older version of php on that server. Will need to do further testing to make sure.

My second attempt was as a new install in a Moodle 3.9 with a newer php 7.3.33, which worked. I can see that you have put a lot of time, thought, and effort into this addition to the plugin. Since this was all on my TODO list, thank you very much for all your hard work. I will see what I can do about integrating your code into the current HQv4.0.2 code which will take me a while due to all the stuff I have added, such as comments, the removal of the file module.js, icon compatibility with Moodle 4, etc.

It will take me a few days to get everything done.

**Comment by drachels** [comment]
Had a few minutes so spent some more time testing and noticed one bug with the, Visible groups, selector.

If I select some group other than, All participants, and then click on the, Rating ranking, button, when I get to the, Rating ranking, page, it lists ALL the enrolled users, but is still showing the same group in the, Visible groups, selector.

I will work more on this tomorrow, as it is getting time for me to make supper.

**Comment by drachels** [comment]
I have adapted your grade code changes into my Moodle 3.11.6+ development site and just fixed a few hundred warnings and errors. So far everything is looking the same as your original code in my Moodle 3.9 test site. I still need to do some more work and testing but should have the code available for the public in another day or two, after testing on Moodle 4.0.

**Comment by drachels** [comment]
When in the Hot Question, Grades > Grade administration > Setup > Gradebook setup > Edit grade item, and trying to change Grade display type from, Default (Real), over to something else, Real (percentage),  I got this:

Invalid course module ID

[More information about this error](http://docs.moodle.org/311/en_us/error/moodle/invalidcoursemodule)
Debug info: SELECT id,course FROM {course_modules} WHERE id IS NULL
[array (
)]
Error code: invalidcoursemodule
Stack trace:

    line 1646 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
    line 1622 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 7319 of /lib/accesslib.php: call to moodle_database->get_record()
    line 809 of /mod/hotquestion/lib.php: call to context_module::instance()
    line 749 of /mod/hotquestion/lib.php: call to hotquestion_get_user_grades()
    line 1401 of /lib/gradelib.php: call to hotquestion_update_grades()
    line 1775 of /lib/grade/grade_item.php: call to grade_update_mod_grades()
    line 674 of /lib/grade/grade_item.php: call to grade_item->refresh_grades()
    line 197 of /grade/edit/tree/item.php: call to grade_item->set_locked()

Output buffer: <br />
<b>Notice</b>: Undefined property: stdClass::$cmid in
<b>/var/www/moodle3dev/mod/hotquestion/lib.php</b> on line
<b>809</b><br />

**Comment by drachels** [comment]
Been making a lot of progress on adapting your contributed code, and making changes as needed. I finally have a site working with a version that is mostly working for Moodle 3.11 and Mood.e 4.0. Log in details are on the login page at http://www.drachels.com/moodle311/
If interested you can go see it in the Hot Question development course.
I still have not been able to figure out why a pre-existing Hot Question activity when edited to use grades, gives some students a bogus grade, that gets corrected as soon as they post a question.

**Comment by drachels** [comment]
Just created branch, MOODLE_410_BETA_RC1, that includes the fix for anonymous posts and also adds your grades and completion capabilities. It does still have a bunch of debugging code in it that I will remove after some more work/fixes that I think it needs.

**Comment by drachels** [comment]
At the present time, I cannot see adding this code to the next release of Hot Question, due to the two bugs I previously mentioned. It seems to me that for bug two, that you are mixing grade and rating code together. For instance, when setting up an activity mod_edit.php shows the settings for using, Grade, but when you dig into lib.php, the function, hotquestion_grade_item_update, is set up  to use a grade_update for Ratings. Anyway, the current code will not give you a correct grade if you try to use a, Scale, instead of, Nothing or points. I just cannot devote any more time for this as I have other items I really need to work on, both for Hot Question and other plugins I maintain.

**Comment by drachels** [comment]
With the release of Hot Question v4.1.0, grades can be used. Over the past few versions, I have done a LOT of checking to make sure that it seems to be working reliably and correctly, so I am going to close this issue.
