### ISSUE TITLE
Non-unique names for database fields

### ISSUE THREAD

**Issue by miotto** [drachels/moodle-mod_hotquestion#56]
Is there a difference between the database fields `assesstimestart` and `assessedtimestart` in the `hotquestion` database? The same question for the database fields `assesstimefinish` and `assessedtimefinish`.

In the file `db/install.xml` only the database fields `assesstimestart` and `assesstimefinish` are defined.

In the file `db/upgrade.php` all the database fields mentioned above are created.

It seems that the fields are not really used at the moment.

Many thanks for your support.

**Comment by drachels** [comment]
Those fields were put there to develop a rating system for Hot Question, but due to my wife's terminal pancreatic cancer, I had not completed development. Recently, I got some contributed code that uses the grading system so those fields will probably be dropped in the next release. Truthfully, it was just an accident on my part that they were included in a release And, yes you are correct, they are not really used at the moment.

**Comment by miotto** [comment]
Thank you for the answer. 
I wish you all the best.

**Comment by drachels** [comment]
Closing this issue as it will be fixed with upcoming v4.1.5 release.
