### ISSUE TITLE
Option to hide unapproved submissions from admin users

### ISSUE THREAD

**Issue by RichieLef** [drachels/moodle-mod_hotquestion#62]
Feature request: Would it be viable to have an option to allow admin users to hide unapproved submissions from their own view?

Currently admin users see unapproved submissions (indicated with a red dot in the 'Approved' column) alongside all other submissions - but it would potentially make the activity more manageable for admins if they could choose to hide these from their own view as well. Maybe they could have an option to have seperate views for 'Approved', 'Unapproved' and 'All'?

**Comment by jgramp** [comment]
+1
I second this request. Even just moving them to the end of the list and having a toggle to hide / show them would help. They do get in the way of the visible entries.

**Comment by drachels** [comment]
I am currently real busy with some major changes to my Diary plugin so it will be a few days before I can try to do a release with any changes for this. However, I did take just a quick look and if you feel up to making a minor code change yourself, you can easily move all the unapproved questions to the bottom of the list.

In the, localib.php file, in the, public function get_questions(), down around line 408:
Change from this:
            ORDER BY tpriority DESC, votecount DESC, q.time DESC', $params);
So that is becomes this:
            ORDER BY q.approved DESC, tpriority DESC, votecount DESC, q.time DESC', $params);

Notice the extra sort item, **q.approved DESC,** that was added. This change will make the unapproved questions move to the bottom of the list. When I get a chance to work on a release, I will also try to include a preference setting so that any individual who can see the column, can hide or show those questions.

**Comment by drachels** [comment]
I have been so frustrated with my other project, that I spent some time this morning working on this. I think I have things working so that it is doing both requests. Unapproved questions are sorted to the bottom of the question list, AND for every user there is a toggle link to show or hide unapproved questions. When there ARE unapproved questions and the toggle is off, a teacher can see them like always and change the approval status. A student in the same situation will see only the approved questions with the toggle ON, or with the toggle OFF they see the approved questions and for unapproved ones, the same old message, This entry is not currently approved for viewing.

I need to do a bunch more testing to make sure, and will include this in the next release when Moodle 4.1 comes out. Before that, maybe by tomorrow, I will post the code to github and on my public test site where you can play with it.

**Comment by drachels** [comment]
I am closing this issue as it is taken care of now with the new sort order and toggle link.

**Comment by jgramp** [comment]
Thank you so much for implementing this :)

It works great!
