### ISSUE TITLE
Close time prevents students to vote

### ISSUE THREAD

**Issue by Kemmotar83** [drachels/moodle-mod_hotquestion#84]
Hi @drachels ,

this issue seems related to issue #68.

My bad I didn't review it after your changes but it seems that, if _Close time_ or _View after close tim_e are enabled, students cannot vote.

In view.php, the if statement in rows 168 and 180 prevents students to vote and remove vote.

In my opinion you should change this 
```
if ((hqavailable::is_hotquestion_ended($hq) && !$hotquestion->viewaftertimeclose)
                    || (has_capability('mod/hotquestion:rate', $context))
```
with this
```
if (!hqavailable::is_hotquestion_ended($hq) ||
                    has_capability('mod/hotquestion:manageentries', $context))
```

This solves the issue (I can provide you a pull request if needed).

Then, I would like to ask you why you want to let teachers vote and remove votes also after Close time.

Giorgio

**Comment by drachels** [comment]
Sorry, but your suggestion is the way it used to be, prior to version 4.1.5. I had requests to enable teachers to have the option  to hide or show, the questions once the HotQuestion activity was closed. I guess someone did not want the students to be able to refer to old activities when post questions in a new one. The current branch named MOODLE_418_STABLE is being worked on to fix this problem.

**Comment by Kemmotar83** [comment]
Hi Al,

before 4.1.5 the if statements didn't exist. I was the one requesting the "View after close time" setting (#68) and now it's ok to check if the activity is closed in order to prevent voting. Fixing the condition will solve the problem.

Thanks again for this plugin,
Giorgio

**Comment by Kemmotar83** [comment]
Hi @drachels ,

maybe I understood the meaning of that condition (I read the documentation with more attention). You want to use Availability (Open / Close Time) only for the question creation, instead voting and commenting will always be available to students.

In this case the condition should be changed as follows:
```
if (!(hqavailable::is_hotquestion_ended($hq) && !$hotquestion->viewaftertimeclose)
                    || (has_capability('mod/hotquestion:rate', $context))
```

Then, I would suggest the introduction of a new setting used to completely close the activity, not allowing also comments and votes.

As I said before, if you need, I can help you.

Thanks again,
Giorgio

**Comment by drachels** [comment]
I think the biggest part of this problem was in the mod_form.php file. The way it was before the activity could be set to have a date for close time and view after close time of yes. It the teacher came back and disabled the close time, the view after close time was immediately disabled from being changed but still was set to yes, when it should have changed to No. 

I have changed the mod_for.php so that now, if the teacher changes their mind and switches from a close time, the viewafterclosetime is set to Null which works with the way the code is written in view.php for case 'vote' and case 'removevote.

Note, that while working on this yesterday, I discovered that many of the capabilities for a non-editing teacher were not working, which required a good bit of changes elsewhere in the code.

I have had so many other things to do, I have not had time to test and make sure this fixes everything due to other life events going on, but I will try to test today.

**Comment by drachels** [comment]
I was busy with other things today, but just now before quitting for the day, I took a quick look at your last suggestion. Unfortunately, it seems to let both students and teachers vote and remove votes after the activity has closed. That is okay for the teachers as they often have to do last minute grading. However, it is NOT okay for a student as it would let them go back and change their grade as well as other students.

**Comment by Kemmotar83** [comment]
Hi @drachels , my last suggestion was made because I was trying to understand the motivation of that condition.

In my opinion _Close time_ should end any student activity. If you agree (so it seems), my first suggestion should solve the problem. If the activity is ended, any vote is refused (maybe also comments), unless you are a teacher.

```
if (!hqavailable::is_hotquestion_ended($hq) ||
                    has_capability('mod/hotquestion:manageentries', $context))
```

Then, you should also work on UI, because, if vote is not permitted than vote buttons should not be displayed.

Thanks again,
Giorgio

**Comment by drachels** [comment]
I have been working on this for the past few days and a few hours this morning while also trying to get a selenium/behat combination working on something a lot faster than what I have right now. Unfortunately, a couple of days ago I realized that something I had started on for non-editing teachers, had never been finished due to major life events. (My deceased wife's cancer diagnosis and treatment proceedings.) Sadly this is not the only place where I seem to have dropped the ball on finishing up something I started.

Anyway, I think I have something working and after trying it on another couple of Moodle versions, if all goes well I will push the changes to github.

**Comment by drachels** [comment]
Well, it appears that the changes do most of what I want.  When a HotQuestion activity is closed and viewafterclose is enabled, students can see the questions, see where they could have voted but didn't, and also so where they did vote. When viewafterclose is disabled, they do not see anything except the old, Not currently available! message and when the activity closed. If the teacher changes back and forth, enable/disable, for the view after close setting, it properly switches now, instead of breaking like it did before.

The thing I still want is when a HotQuestion activity is closed but with viewafterclose enabled, is for the student to also be able to click on the, View grades button, and see details regarding how their grade was calculated. Right now it will not work like it does when the activity is open.

**Comment by Kemmotar83** [comment]
Hi @drachels ,

sorry to bother you again but your last update have not resolved this issue. When "Close time" is enabled students cannot vote before this end date, regardless what is the _viewafterclose_ setting.

Really, if you want to let students vote and remove votes until Close Time, you need to change rows 168-169 and 179-180.

```
if (!hqavailable::is_hotquestion_ended($hq) ||
                    has_capability('mod/hotquestion:manageentries', $context))
```

Giorgio

**Comment by drachels** [comment]
Hmm, I think I may have had a cache problem that caused me to think this was working right. I have some other obligations to take care of over the next couple of days, but will get back on it as soon as I can.

**Comment by drachels** [comment]
I have a new "+" release that seems to be working right. You can test it at https://www.drachels.com/moodle311/course/view.php?id=5#section-2
Log in details are on the log in page.

**Comment by Kemmotar83** [comment]
Hi @drachels ,

now the issue seems to be fixed (thank you!) but I still do not understand the meaning of the last condition (the one including setting _viewaftertimeclose_).

In these rows you check if an action call should be authorized to proceed, regardless view related settings (viewaftertimeclose doesn't have any relation to who or when the action can be done). Moreover, with the last condition you enable to vote when an hotquestion is not active anymore.

```
if (
   // Vote enable when HQ is active
   (hqavailable::is_hotquestion_active($hq))
   // Vote always enable to who has rate capability
   || (has_capability('mod/hotquestion:rate', $context))
   // Vote enable when HQ is NOT active and when viewaftertimeclose is off
   || ((!hqavailable::is_hotquestion_active($hq)) && !$hotquestion->viewaftertimeclose) 
) {
```

Giorgio
