### ISSUE TITLE
Users unable to view hot questions when course is in Read-Only mode

### ISSUE THREAD

**Issue by dragos5436** [drachels/moodle-mod_hotquestion#88]
Hi there,

We've recently had a few users encountering an 'Access denied' error when trying to view hot questions from a Read-Only course:
![image](https://github.com/drachels/moodle-mod_hotquestion/assets/73345838/111fb510-2d38-410c-b734-926a303702b5)

This is currently affecting all users without Site Admin rights.

When turning a course into Read-Only mode, only write permissions should be disabled. However, in this case it seems read permissions are also affected. Could these two be separated so that users could view hot questions from Read-Only courses?

FYI: [Followups for Context Freezing](https://tracker.moodle.org/browse/MDL-63984)

**Comment by drachels** [comment]
I will see what I can do and add this to my TODO list.

**Comment by drachels** [comment]
I seem to have found a simple fix for this, but due to upcoming holiday activities it might take me a few days for further testing and publishing of a new HotQuestion version. If you want to fix your HotQuestion now and can edit the HotQuestion view.php file, as shown in the included picture, add the new line 62 and then modify line 64.
![possiblereadonlycontextfix1](https://github.com/drachels/moodle-mod_hotquestion/assets/1018249/75f19e11-1d95-4c96-8d38-9ec7132b98ee)

**Comment by drachels** [comment]
Note: There are TWO settings involved with this at, Site administration > Development > Experimental > Experimental settings. If your admin can still edit, it is because the second setting, Context freezing applies to administrators, has NOT been selected/enabled.

**Comment by dragos5436** [comment]
Hi,

Thank you very much for the rapid fix provided. 

We are currently using Moodle 4.2 and HotQuestion 4.1.7+ (Build: 2023061100).

This is not an urgent problem so we are happy to wait for you to publish the fix.

Happy Thanksgiving!

Kind regards,

Dragos Suciu
Analyst Developer
UCL
